"""Remove few Mark columns.

Revision ID: 14cf549be3a6
Revises: 41365803970f
Create Date: 2014-12-17 02:05:21.230033

"""

# revision identifiers, used by Alembic.
revision = '14cf549be3a6'
down_revision = '41365803970f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'news_marks_link_id_reader_id_key', 'news_marks', type_='unique')
    op.drop_column('news_marks', 'moment')
    op.drop_column('news_marks', 'unmarked')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_marks', sa.Column('unmarked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('news_marks', sa.Column('moment', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint(u'news_marks_link_id_reader_id_key', 'news_marks', ['link_id', 'reader_id'])
    ### end Alembic commands ###
