"""Drop mark unmarked.

Revision ID: 2baafa2a6683
Revises: 56097006911f
Create Date: 2014-12-19 21:03:20.007110

"""

# revision identifiers, used by Alembic.
revision = '2baafa2a6683'
down_revision = '56097006911f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_marks', 'unmarked')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_marks', sa.Column('unmarked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
