"""Add index to url columns.

Revision ID: 34b32455fb36
Revises: 45f943e55d0e
Create Date: 2015-08-04 13:32:26.666687

"""

# revision identifiers, used by Alembic.
revision = '34b32455fb36'
down_revision = '45f943e55d0e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_news_links_url'), 'news_links', ['url'], unique=True)
    op.drop_constraint(u'news_links_url_key', 'news_links', type_='unique')
    op.create_index(op.f('ix_twitter_statuses_url'), 'twitter_statuses', ['url'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_statuses_url'), table_name='twitter_statuses')
    op.create_unique_constraint(u'news_links_url_key', 'news_links', ['url'])
    op.drop_index(op.f('ix_news_links_url'), table_name='news_links')
    ### end Alembic commands ###
