"""More indexes on Twitter Statuses.

Revision ID: 3661b9d20d1f
Revises: 4fa4a8dfdf3c
Create Date: 2015-11-03 09:23:20.580234

"""

# revision identifiers, used by Alembic.
revision = '3661b9d20d1f'
down_revision = '4fa4a8dfdf3c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_statuses_created_at'), 'twitter_statuses', ['created_at'], unique=False)
    op.create_index(op.f('ix_twitter_statuses_state'), 'twitter_statuses', ['state'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_statuses_state'), table_name='twitter_statuses')
    op.drop_index(op.f('ix_twitter_statuses_created_at'), table_name='twitter_statuses')
    ### end Alembic commands ###
