"""Links that are known are actually ignored.

Revision ID: 36938770b1b2
Revises: b1c77cc604f
Create Date: 2015-03-19 10:37:28.003959

"""

# revision identifiers, used by Alembic.
revision = '36938770b1b2'
down_revision = 'b1c77cc604f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_links', sa.Column('ignored', sa.Boolean(), nullable=True))
    op.drop_column('news_links', 'known')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_links', sa.Column('known', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('news_links', 'ignored')
    ### end Alembic commands ###
