"""Added user roles.

Revision ID: 36f557323a95
Revises: 36938770b1b2
Create Date: 2015-05-04 13:18:55.120400

"""

# revision identifiers, used by Alembic.
revision = '36f557323a95'
down_revision = '36938770b1b2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auth_users_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_users_roles')
    op.drop_table('auth_roles')
    ### end Alembic commands ###
