"""Added back integer featured reader.

Revision ID: 383e7261db09
Revises: 4d2841b3c0ab
Create Date: 2015-06-27 13:21:00.438858

"""

# revision identifiers, used by Alembic.
revision = '383e7261db09'
down_revision = '4d2841b3c0ab'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_readers', sa.Column('featured', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_readers', 'featured')
    ### end Alembic commands ###
