"""Reader attributes.

Revision ID: 3da44d4e8334
Revises: 48a2c95c625
Create Date: 2015-05-08 13:46:37.357787

"""

# revision identifiers, used by Alembic.
revision = '3da44d4e8334'
down_revision = '48a2c95c625'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_readers', sa.Column('bot', sa.Boolean(), nullable=True))
    op.add_column('news_readers', sa.Column('featured', sa.Boolean(), nullable=True))
    op.add_column('news_readers', sa.Column('ignored', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_readers', 'ignored')
    op.drop_column('news_readers', 'featured')
    op.drop_column('news_readers', 'bot')
    ### end Alembic commands ###
