"""Add extra Mark columns.

Revision ID: 3e25f44c7053
Revises: 14cf549be3a6
Create Date: 2014-12-17 02:08:13.220463

"""

# revision identifiers, used by Alembic.
revision = '3e25f44c7053'
down_revision = '14cf549be3a6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from database.news.models import Mark

def upgrade():
    ### Adding Enum type if missing
    # https://bitbucket.org/zzzeek/alembic/issue/89/opadd_column-and-opdrop_column-should
    bind = op.get_bind()
    Source = Mark.__table__.c.source.type
    impl = Source.dialect_impl(bind.dialect)
    impl.create(bind, checkfirst=True)

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_marks', sa.Column('moment', sa.BigInteger(), nullable=False))
    op.add_column('news_marks', sa.Column('source', sa.Enum('none', 'twitter', 'web', 'api', name='mark_sources'), nullable=False))
    op.add_column('news_marks', sa.Column('unmarked', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_marks', 'unmarked')
    op.drop_column('news_marks', 'source')
    op.drop_column('news_marks', 'moment')
    ### end Alembic commands ###
