"""Initial revision

Revision ID: 41365803970f
Revises: 
Create Date: 2014-12-16 00:51:39.180045

"""

# revision identifiers, used by Alembic.
revision = '41365803970f'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_links',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('broken', sa.Boolean(), nullable=True),
    sa.Column('known', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('url')
    )
    op.create_table('twitter_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('screen_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.Column('friends_count', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('ignored', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_name'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('auth_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('screen_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('screen_name')
    )
    op.create_table('twitter_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['twitter_users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('news_readers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('auth_user_id', sa.BigInteger(), nullable=True),
    sa.Column('twitter_user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['twitter_user_id'], ['twitter_users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_user_id'),
    sa.UniqueConstraint('twitter_user_id')
    )
    op.create_table('twitter_statuses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('none', 'busy', 'fail', 'done', name='job_states'), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['news_links.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['twitter_users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_id')
    )
    op.create_table('twitter_timelines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('since_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.Enum('none', 'busy', 'fail', 'done', name='job_states'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_check', sa.DateTime(), nullable=True),
    sa.Column('prev_check', sa.DateTime(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('failures', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['twitter_users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('news_marks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.Column('reader_id', sa.BigInteger(), nullable=False),
    sa.Column('moment', sa.Integer(), nullable=False),
    sa.Column('unmarked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['news_links.id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['news_readers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_id', 'reader_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_marks')
    op.drop_table('twitter_timelines')
    op.drop_table('twitter_statuses')
    op.drop_table('news_readers')
    op.drop_table('twitter_tokens')
    op.drop_table('auth_users')
    op.drop_table('twitter_users')
    op.drop_table('news_links')
    ### end Alembic commands ###
