"""Twitter timeline types.

Revision ID: 45f943e55d0e
Revises: df4cc672af2
Create Date: 2015-07-04 04:51:09.655364

"""

# revision identifiers, used by Alembic.
revision = '45f943e55d0e'
down_revision = 'df4cc672af2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

def upgrade():
    ### Adding Enum type if missing
    # https://bitbucket.org/zzzeek/alembic/issue/89/opadd_column-and-opdrop_column-should
    from database.twitter.models import Timeline
    bind = op.get_bind()
    Type = Timeline.__table__.c.type.type
    impl = Type.dialect_impl(bind.dialect)
    impl.create(bind, checkfirst=True)

    ### Adding non nullable column
    op.add_column('twitter_timelines', sa.Column('type', sa.Enum('home', 'user', 'list', name='timeline_types'), nullable=True))
    twitter_timelines_type = table('twitter_timelines', column('type'))
    op.execute(twitter_timelines_type.update().values(type=Timeline.Type.HOME))
    op.alter_column('twitter_timelines', 'type', nullable=False)

    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('twitter_timelines', sa.Column('type', sa.Enum('home', 'user', 'list', name='timeline_types'), nullable=False))
    op.add_column('twitter_timelines', sa.Column('list_id', sa.BigInteger(), nullable=True))
    op.drop_constraint(u'twitter_timelines_user_id_key', 'twitter_timelines', type_='unique')
    op.create_unique_constraint('twitter_timelines_list_id_unique', 'twitter_timelines', ['list_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('twitter_timelines_list_id_unique', 'twitter_timelines', type_='unique')
    op.create_unique_constraint(u'twitter_timelines_user_id_key', 'twitter_timelines', ['user_id'])
    op.drop_column('twitter_timelines', 'type')
    op.drop_column('twitter_timelines', 'list_id')
    ### end Alembic commands ###
