"""Rename mark to pick.

Revision ID: 4cd44771c99b
Revises: 3514151fcb3b
Create Date: 2015-05-18 19:10:13.375760

"""

# revision identifiers, used by Alembic.
revision = '4cd44771c99b'
down_revision = '3514151fcb3b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('news_picks',
    # sa.Column('id', sa.BigInteger(), nullable=False),
    # sa.Column('link_id', sa.BigInteger(), nullable=False),
    # sa.Column('reader_id', sa.BigInteger(), nullable=False),
    # sa.Column('moment', sa.BigInteger(), nullable=False),
    # sa.Column('source', sa.Enum('none', 'twitter', 'web', 'api', name='pick_sources'), nullable=False),
    # sa.Column('twitter_status_id', sa.BigInteger(), nullable=True),
    # sa.Column('unpicked', sa.Boolean(), nullable=True),
    # sa.ForeignKeyConstraint(['link_id'], ['news_links.id'], ),
    # sa.ForeignKeyConstraint(['reader_id'], ['news_readers.id'], ),
    # sa.ForeignKeyConstraint(['twitter_status_id'], ['twitter_statuses.status_id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('twitter_status_id')
    # )    
    # op.drop_table('news_marks')
    op.rename_table('news_marks', 'news_picks')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('news_marks',
    # sa.Column('id', sa.BIGINT(), nullable=False),
    # sa.Column('link_id', sa.BIGINT(), autoincrement=False, nullable=False),
    # sa.Column('reader_id', sa.BIGINT(), autoincrement=False, nullable=False),
    # sa.Column('moment', sa.BIGINT(), autoincrement=False, nullable=False),
    # sa.Column('source', postgresql.ENUM(u'none', u'twitter', u'web', u'api', name='mark_sources'), autoincrement=False, nullable=False),
    # sa.Column('twitter_status_id', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('unmarked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['link_id'], [u'news_links.id'], name=u'news_marks_link_id_fkey'),
    # sa.ForeignKeyConstraint(['reader_id'], [u'news_readers.id'], name=u'news_marks_reader_id_fkey'),
    # sa.ForeignKeyConstraint(['twitter_status_id'], [u'twitter_statuses.status_id'], name=u'news_marks_twitter_status_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name=u'news_marks_pkey')
    # )
    # op.drop_table('news_picks')
    op.rename_table('news_picks', 'news_marks')
    ### end Alembic commands ###
