"""Temp rem featured reader.

Revision ID: 4d2841b3c0ab
Revises: 51a524404f50
Create Date: 2015-06-27 13:19:59.978954

"""

# revision identifiers, used by Alembic.
revision = '4d2841b3c0ab'
down_revision = '51a524404f50'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_readers', 'featured')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_readers', sa.Column('featured', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
