"""Status indexes on foreign keys

Revision ID: 4fa4a8dfdf3c
Revises: 34b32455fb36
Create Date: 2015-08-24 19:58:16.374160

"""

# revision identifiers, used by Alembic.
revision = '4fa4a8dfdf3c'
down_revision = '34b32455fb36'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_statuses_link_id'), 'twitter_statuses', ['link_id'], unique=False)
    op.create_index(op.f('ix_twitter_statuses_user_id'), 'twitter_statuses', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_statuses_user_id'), table_name='twitter_statuses')
    op.drop_index(op.f('ix_twitter_statuses_link_id'), table_name='twitter_statuses')
    ### end Alembic commands ###
