"""No unmark for now.

Revision ID: 51a524404f50
Revises: 4cd44771c99b
Create Date: 2015-05-18 20:17:57.805210

"""

# revision identifiers, used by Alembic.
revision = '51a524404f50'
down_revision = '4cd44771c99b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_picks', 'unmarked')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_picks', sa.Column('unmarked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
