"""Login tracking data.

Revision ID: 54792542f32
Revises: 36938770b1b2
Create Date: 2015-05-06 22:40:56.749925

"""

# revision identifiers, used by Alembic.
revision = '54792542f32'
down_revision = '36938770b1b2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('auth_users', sa.Column('last_login_ip', sa.String(), nullable=True))
    op.add_column('auth_users', sa.Column('login_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_users', 'login_count')
    op.drop_column('auth_users', 'last_login_ip')
    op.drop_column('auth_users', 'last_login_at')
    ### end Alembic commands ###
