"""Mark twitter status id

Revision ID: 56097006911f
Revises: 3e25f44c7053
Create Date: 2014-12-18 22:09:54.003514

"""

# revision identifiers, used by Alembic.
revision = '56097006911f'
down_revision = '3e25f44c7053'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_marks', sa.Column('twitter_status_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'news_marks', ['twitter_status_id'])
    op.create_foreign_key(None, 'news_marks', 'twitter_statuses', ['twitter_status_id'], ['status_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_marks', type_='foreignkey')
    op.drop_constraint(None, 'news_marks', type_='unique')
    op.drop_column('news_marks', 'twitter_status_id')
    ### end Alembic commands ###
