"""Add unmarked back.

Revision ID: 77b22024754
Revises: 2baafa2a6683
Create Date: 2014-12-19 21:03:44.940663

"""

# revision identifiers, used by Alembic.
revision = '77b22024754'
down_revision = '2baafa2a6683'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_marks', sa.Column('unmarked', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_marks', 'unmarked')
    ### end Alembic commands ###
