"""User login tracking.

Revision ID: 77e8c50e98
Revises: 36f557323a95
Create Date: 2015-05-04 14:31:39.826002

"""

# revision identifiers, used by Alembic.
revision = '77e8c50e98'
down_revision = '36f557323a95'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('auth_users', sa.Column('current_login_at', sa.DateTime(), nullable=True))
    op.add_column('auth_users', sa.Column('current_login_ip', sa.String(), nullable=True))
    op.add_column('auth_users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('auth_users', sa.Column('last_login_ip', sa.String(), nullable=True))
    op.add_column('auth_users', sa.Column('login_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_users', 'login_count')
    op.drop_column('auth_users', 'last_login_ip')
    op.drop_column('auth_users', 'last_login_at')
    op.drop_column('auth_users', 'current_login_ip')
    op.drop_column('auth_users', 'current_login_at')
    op.drop_column('auth_users', 'active')
    ### end Alembic commands ###
